/* eslint-disable prettier/prettier */

import { NotificationEventModel } from '../models/notification-event.model';
import {
  BLOCKCHAIN_BINANCE_MAINNET_CHAIN_ID,
  BLOCKCHAIN_BINANCE_MAINNET_SLUG,
  BLOCKCHAIN_BINANCE_TESTNET_CHAIN_ID,
  BLOCKCHAIN_BINANCE_TESTNET_SLUG,
  BLOCKCHAIN_ETHEREUM_CHAIN_ID,
  BLOCKCHAIN_ETHEREUM_SLUG,
  BLOCKCHAIN_GOERLI_CHAIN_ID,
  BLOCKCHAIN_GOERLI_SLUG,
  BLOCKCHAIN_KOVAN_CHAIN_ID,
  BLOCKCHAIN_KOVAN_SLUG,
  BLOCKCHAIN_MUMBAI_CHAIN_ID,
  BLOCKCHAIN_MUMBAI_SLUG,
  BLOCKCHAIN_POLYGON_CHAIN_ID,
  BLOCKCHAIN_POLYGON_SLUG,
  BLOCKCHAIN_RINKEBY_CHAIN_ID,
  BLOCKCHAIN_RINKEBY_SLUG,
  BLOCKCHAIN_ROPSTEN_CHAIN_ID,
  BLOCKCHAIN_ROPSTEN_SLUG,
  NOTIFICATION_EVENTS_AUCTION_EXPIRATION,
  NOTIFICATION_EVENTS_BID_ACTIVITY,
  NOTIFICATION_EVENTS_ITEM_SOLD,
  NOTIFICATION_EVENTS_OPENSEA_NEWSLETTER,
  NOTIFICATION_EVENTS_OUTBID,
  NOTIFICATION_EVENTS_OWNED_ITEM_UPDATES,
  NOTIFICATION_EVENTS_PRICE_CHANGE,
  NOTIFICATION_EVENTS_SUCCESSFULLY_PURCHASED,
  STATUS_ACTIVE,
  STATUS_INACTIVE,
} from './coreconstants';

export const countryList = {
  AF: 'Afghanistan',
  AL: 'Albania',
  DZ: 'Algeria',
  AS: 'American Samoa',
  AD: 'Andorra',
  AO: 'Angola',
  AI: 'Anguilla',
  AQ: 'Antarctica',
  AG: 'Antigua and Barbuda',
  AR: 'Argentina',
  AM: 'Armenia',
  AW: 'Aruba',
  AU: 'Australia',
  AT: 'Austria',
  AZ: 'Azerbaijan',
  BS: 'Bahamas (the)',
  BH: 'Bahrain',
  BD: 'Bangladesh',
  BB: 'Barbados',
  BY: 'Belarus',
  BE: 'Belgium',
  BZ: 'Belize',
  BJ: 'Benin',
  BM: 'Bermuda',
  BT: 'Bhutan',
  BO: 'Bolivia (Plurinational State of)',
  BQ: 'Bonaire, Sint Eustatius and Saba',
  BA: 'Bosnia and Herzegovina',
  BW: 'Botswana',
  BV: 'Bouvet Island',
  BR: 'Brazil',
  IO: 'British Indian Ocean Territory (the)',
  BN: 'Brunei Darussalam',
  BG: 'Bulgaria',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  CV: 'Cabo Verde',
  KH: 'Cambodia',
  CM: 'Cameroon',
  CA: 'Canada',
  KY: 'Cayman Islands (the)',
  CF: 'Central African Republic (the)',
  TD: 'Chad',
  CL: 'Chile',
  CN: 'China',
  CX: 'Christmas Island',
  CC: 'Cocos (Keeling) Islands (the)',
  CO: 'Colombia',
  KM: 'Comoros (the)',
  CD: 'Congo (the Democratic Republic of the)',
  CG: 'Congo (the)',
  CK: 'Cook Islands (the)',
  CR: 'Costa Rica',
  HR: 'Croatia',
  CU: 'Cuba',
  CW: 'Curaçao',
  CY: 'Cyprus',
  CZ: 'Czechia',
  CI: "Côte d'Ivoire",
  DK: 'Denmark',
  DJ: 'Djibouti',
  DM: 'Dominica',
  DO: 'Dominican Republic (the)',
  EC: 'Ecuador',
  EG: 'Egypt',
  SV: 'El Salvador',
  GQ: 'Equatorial Guinea',
  ER: 'Eritrea',
  EE: 'Estonia',
  SZ: 'Eswatini',
  ET: 'Ethiopia',
  FK: 'Falkland Islands (the) [Malvinas]',
  FO: 'Faroe Islands (the)',
  FJ: 'Fiji',
  FI: 'Finland',
  FR: 'France',
  GF: 'French Guiana',
  PF: 'French Polynesia',
  TF: 'French Southern Territories (the)',
  GA: 'Gabon',
  GM: 'Gambia (the)',
  GE: 'Georgia',
  DE: 'Germany',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GR: 'Greece',
  GL: 'Greenland',
  GD: 'Grenada',
  GP: 'Guadeloupe',
  GU: 'Guam',
  GT: 'Guatemala',
  GG: 'Guernsey',
  GN: 'Guinea',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HT: 'Haiti',
  HM: 'Heard Island and McDonald Islands',
  VA: 'Holy See (the)',
  HN: 'Honduras',
  HK: 'Hong Kong',
  HU: 'Hungary',
  IS: 'Iceland',
  IN: 'India',
  ID: 'Indonesia',
  IR: 'Iran (Islamic Republic of)',
  IQ: 'Iraq',
  IE: 'Ireland',
  IM: 'Isle of Man',
  IL: 'Israel',
  IT: 'Italy',
  JM: 'Jamaica',
  JP: 'Japan',
  JE: 'Jersey',
  JO: 'Jordan',
  KZ: 'Kazakhstan',
  KE: 'Kenya',
  KI: 'Kiribati',
  KP: "Korea (the Democratic People's Republic of)",
  KR: 'Korea (the Republic of)',
  KW: 'Kuwait',
  KG: 'Kyrgyzstan',
  LA: "Lao People's Democratic Republic (the)",
  LV: 'Latvia',
  LB: 'Lebanon',
  LS: 'Lesotho',
  LR: 'Liberia',
  LY: 'Libya',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  MO: 'Macao',
  MG: 'Madagascar',
  MW: 'Malawi',
  MY: 'Malaysia',
  MV: 'Maldives',
  ML: 'Mali',
  MT: 'Malta',
  MH: 'Marshall Islands (the)',
  MQ: 'Martinique',
  MR: 'Mauritania',
  MU: 'Mauritius',
  YT: 'Mayotte',
  MX: 'Mexico',
  FM: 'Micronesia (Federated States of)',
  MD: 'Moldova (the Republic of)',
  MC: 'Monaco',
  MN: 'Mongolia',
  ME: 'Montenegro',
  MS: 'Montserrat',
  MA: 'Morocco',
  MZ: 'Mozambique',
  MM: 'Myanmar',
  NA: 'Namibia',
  NR: 'Nauru',
  NP: 'Nepal',
  NL: 'Netherlands (the)',
  NC: 'New Caledonia',
  NZ: 'New Zealand',
  NI: 'Nicaragua',
  NE: 'Niger (the)',
  NG: 'Nigeria',
  NU: 'Niue',
  NF: 'Norfolk Island',
  MP: 'Northern Mariana Islands (the)',
  NO: 'Norway',
  OM: 'Oman',
  PK: 'Pakistan',
  PW: 'Palau',
  PS: 'Palestine, State of',
  PA: 'Panama',
  PG: 'Papua New Guinea',
  PY: 'Paraguay',
  PE: 'Peru',
  PH: 'Philippines (the)',
  PN: 'Pitcairn',
  PL: 'Poland',
  PT: 'Portugal',
  PR: 'Puerto Rico',
  QA: 'Qatar',
  MK: 'Republic of North Macedonia',
  RO: 'Romania',
  RU: 'Russian Federation (the)',
  RW: 'Rwanda',
  RE: 'Réunion',
  BL: 'Saint Barthélemy',
  SH: 'Saint Helena, Ascension and Tristan da Cunha',
  KN: 'Saint Kitts and Nevis',
  LC: 'Saint Lucia',
  MF: 'Saint Martin (French part)',
  PM: 'Saint Pierre and Miquelon',
  VC: 'Saint Vincent and the Grenadines',
  WS: 'Samoa',
  SM: 'San Marino',
  ST: 'Sao Tome and Principe',
  SA: 'Saudi Arabia',
  SN: 'Senegal',
  RS: 'Serbia',
  SC: 'Seychelles',
  SL: 'Sierra Leone',
  SG: 'Singapore',
  SX: 'Sint Maarten (Dutch part)',
  SK: 'Slovakia',
  SI: 'Slovenia',
  SB: 'Solomon Islands',
  SO: 'Somalia',
  ZA: 'South Africa',
  GS: 'South Georgia and the South Sandwich Islands',
  SS: 'South Sudan',
  ES: 'Spain',
  LK: 'Sri Lanka',
  SD: 'Sudan (the)',
  SR: 'Suriname',
  SJ: 'Svalbard and Jan Mayen',
  SE: 'Sweden',
  CH: 'Switzerland',
  SY: 'Syrian Arab Republic',
  TW: 'Taiwan',
  TJ: 'Tajikistan',
  TZ: 'Tanzania, United Republic of',
  TH: 'Thailand',
  TL: 'Timor-Leste',
  TG: 'Togo',
  TK: 'Tokelau',
  TO: 'Tonga',
  TT: 'Trinidad and Tobago',
  TN: 'Tunisia',
  TR: 'Turkey',
  TM: 'Turkmenistan',
  TC: 'Turks and Caicos Islands (the)',
  TV: 'Tuvalu',
  UG: 'Uganda',
  UA: 'Ukraine',
  AE: 'United Arab Emirates (the)',
  GB: 'United Kingdom of Great Britain and Northern Ireland (the)',
  UM: 'United States Minor Outlying Islands (the)',
  US: 'United States of America (the)',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VU: 'Vanuatu',
  VE: 'Venezuela (Bolivarian Republic of)',
  VN: 'Viet Nam',
  VG: 'Virgin Islands (British)',
  VI: 'Virgin Islands (U.S.)',
  WF: 'Wallis and Futuna',
  EH: 'Western Sahara',
  YE: 'Yemen',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
  AX: 'Åland Islands',
};

export const domainData = {
  name: 'NFTexchange',
  version: '1',
  chainId: null,
  verifyingContract: '',
};

export const sellType = {
  SellOrder: [
    { name: '_nonce', type: 'string' },
    { name: '_startsAt', type: 'uint' },
    { name: '_expiresAt', type: 'uint' },
    { name: '_nftContract', type: 'address' },
    { name: '_nftTokenId', type: 'uint256' },
    { name: '_paymentTokenContract', type: 'address' },
    { name: '_seller', type: 'address' },
    { name: '_royaltyPayTo', type: 'address' },
    { name: '_sellerAmount', type: 'uint256' },
    { name: '_feeAmount', type: 'uint256' },
    { name: '_royaltyAmount', type: 'uint256' },
    { name: '_totalAmount', type: 'uint256' },
  ],
};

export const buyType = {
  BuyOrder: [
    { name: '_nonce', type: 'string' },
    { name: '_startsAt', type: 'uint' },
    { name: '_expiresAt', type: 'uint' },
    { name: '_nftContract', type: 'address' },
    { name: '_nftTokenId', type: 'uint256' },
    { name: '_paymentTokenContract', type: 'address' },
    { name: '_buyer', type: 'address' },
    { name: '_royaltyPayTo', type: 'address' },
    { name: '_sellerAmount', type: 'uint256' },
    { name: '_feeAmount', type: 'uint256' },
    { name: '_royaltyAmount', type: 'uint256' },
    { name: '_totalAmount', type: 'uint256' },
  ],
};

export const BlockchainSlugList = [
  BLOCKCHAIN_RINKEBY_SLUG,
  BLOCKCHAIN_ROPSTEN_SLUG,
  BLOCKCHAIN_GOERLI_SLUG,
  BLOCKCHAIN_KOVAN_SLUG,
  BLOCKCHAIN_BINANCE_TESTNET_SLUG,
  BLOCKCHAIN_MUMBAI_SLUG,
  BLOCKCHAIN_ETHEREUM_SLUG,
  BLOCKCHAIN_POLYGON_SLUG,
  BLOCKCHAIN_BINANCE_MAINNET_SLUG,
];

export const BlockchainSlugMapping = {
  [BLOCKCHAIN_RINKEBY_SLUG]:{
    key:'testnet',
    title: 'RinkeBy',
    chainId: BLOCKCHAIN_RINKEBY_CHAIN_ID
  },
  [BLOCKCHAIN_ROPSTEN_SLUG]:{
    key:'testnet',
    title: 'Ropsten',
    chainId: BLOCKCHAIN_ROPSTEN_CHAIN_ID
  },
  [BLOCKCHAIN_GOERLI_SLUG]:{
    key:'testnet',
    title: 'Goerli',
    chainId: BLOCKCHAIN_GOERLI_CHAIN_ID
  },
  [BLOCKCHAIN_KOVAN_SLUG]:{
    key:'testnet',
    title: 'Kovan',
    chainId: BLOCKCHAIN_KOVAN_CHAIN_ID
  },
  [BLOCKCHAIN_BINANCE_TESTNET_SLUG]:{
    key:'testnet',
    title: 'Binance Testnet',
    chainId: BLOCKCHAIN_BINANCE_TESTNET_CHAIN_ID
  },
  [BLOCKCHAIN_MUMBAI_SLUG]:{
    key:'testnet',
    title: 'Mumbai',
    chainId: BLOCKCHAIN_MUMBAI_CHAIN_ID
  },
  [BLOCKCHAIN_ETHEREUM_SLUG]:{
    key:'mainnet',
    title: 'Ethereum',
    chainId: BLOCKCHAIN_ETHEREUM_CHAIN_ID
  },
  [BLOCKCHAIN_POLYGON_SLUG]:{
    key:'mainnet',
    title: 'Polygon',
    chainId: BLOCKCHAIN_POLYGON_CHAIN_ID
  },
  [BLOCKCHAIN_BINANCE_MAINNET_SLUG]:{
    key:'mainnet',
    title: 'Binance',
    chainId: BLOCKCHAIN_BINANCE_MAINNET_CHAIN_ID
  },
};

export const NotificationEvents : Array<NotificationEventModel> = [
  {
    id: NOTIFICATION_EVENTS_ITEM_SOLD,
    title: __('Item Sold'),
    description: 'When someone purchased one of your items',
    status: STATUS_ACTIVE,
  },
  {
    id: NOTIFICATION_EVENTS_BID_ACTIVITY,
    title: __('Bid Activity'),
    description: __('When someone bids on one of your items'),
    status: STATUS_ACTIVE,
  },
  {
    id: NOTIFICATION_EVENTS_PRICE_CHANGE,
    title: __('Price Change'),
    description: __('When an item you made an offer on changes in price'),
    status: STATUS_INACTIVE,
  },
  {
    id: NOTIFICATION_EVENTS_AUCTION_EXPIRATION,
    title: __('Auction Expiration'),
    description: __('When a timed auction you created ends'),
    status: STATUS_ACTIVE,
  },
  {
    id: NOTIFICATION_EVENTS_OUTBID,
    title: __('Outbid'),
    description: __('When an offer you placed is exceeded by another user'),
    status: STATUS_INACTIVE,
  },
  {
    id: NOTIFICATION_EVENTS_OWNED_ITEM_UPDATES,
    title: __('Owned Item Updates'),
    description:
      __('When a significant update occurs for one of the items you have purchased on OpenSea'),
    status: STATUS_INACTIVE,
  },
  {
    id: NOTIFICATION_EVENTS_SUCCESSFULLY_PURCHASED,
    title: __('Successful Purchase'),
    description: __('When you successfully buy an item'),
    status: STATUS_ACTIVE,
  },
  {
    id: NOTIFICATION_EVENTS_OPENSEA_NEWSLETTER,
    title: __('OpenSea Newsletter'),
    description: __('Occasional updates from the OpenSea team'),
    status: STATUS_INACTIVE,
  },
];

export const RESTRICTED_KEY_WORDS= ['create', 'edit', 'delete', 'update'];

function __(arg0: string): string {
  return arg0;
}

