import { PrismaClient } from '@prisma/client';
import {
  NULL_ETH_ADDRESS,
  PAYMENT_TOKEN_TYPE_NATIVE_COIN,
  PAYMENT_TOKEN_TYPE_TOKEN,
  STATUS_ACTIVE,
  STATUS_INACTIVE,
} from '../../src/app/helpers/coreconstants';

export async function seedPaymentToken(prisma: PrismaClient) {
  await prisma.paymentToken.createMany({
    data: [
      {
        blockchain_id: 1,
        name: 'Ether',
        type: PAYMENT_TOKEN_TYPE_NATIVE_COIN,
        contract_address: NULL_ETH_ADDRESS,
        token_symbol: 'ETH',
        min_amount_to_execute_auction: 0.1,
        total_decimal: 18,
        is_default: STATUS_ACTIVE,
        is_wrapable: STATUS_ACTIVE,
        logo: 'images/tokens/eth.svg',
        sync_rate_status: STATUS_ACTIVE,
      },
      {
        blockchain_id: 1,
        name: 'Wrapped Ether',
        type: PAYMENT_TOKEN_TYPE_TOKEN,
        min_amount_to_execute_auction: 0.1,
        contract_address: '0xc778417E063141139Fce010982780140Aa0cD5Ab',
        token_symbol: 'WETH',
        total_decimal: 18,
        is_default: STATUS_ACTIVE,
        is_wrapable: STATUS_ACTIVE,
        logo: 'images/tokens/weth.svg',
        sync_rate_status: STATUS_ACTIVE,
      },
      {
        blockchain_id: 1,
        name: 'DK Free Token',
        type: PAYMENT_TOKEN_TYPE_TOKEN,
        min_amount_to_execute_auction: 10,
        contract_address: '0x63Bdb4DA767A1EB37c1E4203E4f596ECe3a653a2',
        token_symbol: 'DKFT20',
        total_decimal: 18,
        is_default: STATUS_INACTIVE,
        is_wrapable: STATUS_INACTIVE,
        logo: 'images/tokens/dkft20.png',
        sync_rate_status: STATUS_INACTIVE,
      },
      {
        blockchain_id: 2,
        name: 'Matic',
        type: PAYMENT_TOKEN_TYPE_NATIVE_COIN,
        contract_address: NULL_ETH_ADDRESS,
        token_symbol: 'MATIC',
        min_amount_to_execute_auction: 0.1,
        total_decimal: 18,
        is_default: STATUS_ACTIVE,
        is_wrapable: STATUS_ACTIVE,
        logo: 'images/tokens/matic.png',
        sync_rate_status: STATUS_ACTIVE,
      },
      {
        blockchain_id: 2,
        name: 'Wrapped Matic',
        type: PAYMENT_TOKEN_TYPE_TOKEN,
        min_amount_to_execute_auction: 0.1,
        contract_address: '0x0228A456B4719Dd584230202b9FF47c986Ad7893',
        token_symbol: 'WMATIC',
        total_decimal: 18,
        is_default: STATUS_ACTIVE,
        is_wrapable: STATUS_ACTIVE,
        logo: 'images/tokens/wmatic.png',
        sync_rate_status: STATUS_ACTIVE,
      },
      {
        blockchain_id: 2,
        name: 'DK Free Token',
        type: PAYMENT_TOKEN_TYPE_TOKEN,
        min_amount_to_execute_auction: 10,
        contract_address: '0x57058c97C47358183e1a567d298f1a832Bb2361C',
        token_symbol: 'DKFT20',
        total_decimal: 18,
        is_default: STATUS_INACTIVE,
        is_wrapable: STATUS_INACTIVE,
        logo: 'images/tokens/dkft20.png',
        sync_rate_status: STATUS_INACTIVE,
      },
      {
        blockchain_id: 3,
        name: 'Binance Coin',
        type: PAYMENT_TOKEN_TYPE_NATIVE_COIN,
        contract_address: NULL_ETH_ADDRESS,
        token_symbol: 'BNB',
        min_amount_to_execute_auction: 0.1,
        total_decimal: 18,
        is_default: STATUS_ACTIVE,
        is_wrapable: STATUS_ACTIVE,
        logo: 'images/tokens/bnb.png',
        sync_rate_status: STATUS_ACTIVE,
      },
      {
        blockchain_id: 3,
        name: 'Wrapped BNB',
        type: PAYMENT_TOKEN_TYPE_TOKEN,
        min_amount_to_execute_auction: 0.1,
        contract_address: '0xD7A150bCC7666E130e829114404C84A22A344d5E',
        token_symbol: 'WBNB',
        total_decimal: 18,
        is_default: STATUS_ACTIVE,
        is_wrapable: STATUS_ACTIVE,
        logo: 'images/tokens/wbnb.svg',
        sync_rate_status: STATUS_ACTIVE,
      },
      {
        blockchain_id: 3,
        name: 'DK Free Token',
        type: PAYMENT_TOKEN_TYPE_TOKEN,
        min_amount_to_execute_auction: 10,
        contract_address: '0x9498Cf5eF071cabADf6d47bC075E3Cc621E59707',
        token_symbol: 'DKFT20',
        total_decimal: 18,
        is_default: STATUS_INACTIVE,
        is_wrapable: STATUS_INACTIVE,
        logo: 'images/tokens/dkft20.png',
        sync_rate_status: STATUS_INACTIVE,
      },
    ],
    skipDuplicates: true,
  });
}
