import {
  ITEM_EVENT_TYPE_MINT,
  ITEM_EVENT_TYPE_LISTINGS,
  ITEM_EVENT_TYPE_BIDS,
  ITEM_EVENT_TYPE_SALES,
  ITEM_EVENT_TYPE_TRANSFERS,
  ITEM_EVENT_TYPE_BUY_OFFERS,
  ITEM_EVENT_TYPE_LISTING_CANCEL,
  ITEM_EVENT_TYPE_BUY_OFFER_CANCEL,
  ITEM_EVENT_TYPE_BID_CANCEL,
  ITEM_FILTER_STATUS_BUY_NOW,
  ITEM_FILTER_STATUS_ON_AUCTION,
  ITEM_FILTER_STATUS_NEW,
  ITEM_FILTER_STATUS_HAS_OFFERS,
  SORTING_VALUE_NEWEST,
  SORTING_VALUE_OLDEST,
  SORTING_VALUE_PRICE_L2H,
  SORTING_VALUE_PRICE_H2L,
  SORTING_VALUE_MOST_FAVOURITE,
  SORTING_VALUE_MOST_VIEWED,
  BLOCKCHAIN_BINANCE_MAINNET_SLUG,
  BLOCKCHAIN_BINANCE_TESTNET_SLUG,
  BLOCKCHAIN_ETHEREUM_SLUG,
  BLOCKCHAIN_GOERLI_SLUG,
  BLOCKCHAIN_KOVAN_SLUG,
  BLOCKCHAIN_MUMBAI_SLUG,
  BLOCKCHAIN_POLYGON_SLUG,
  BLOCKCHAIN_RINKEBY_SLUG,
  BLOCKCHAIN_ROPSTEN_SLUG,
  BLOCKCHAIN_BINANCE_MAINNET_CHAIN_ID,
  BLOCKCHAIN_BINANCE_TESTNET_CHAIN_ID,
  BLOCKCHAIN_ETHEREUM_CHAIN_ID,
  BLOCKCHAIN_GOERLI_CHAIN_ID,
  BLOCKCHAIN_KOVAN_CHAIN_ID,
  BLOCKCHAIN_MUMBAI_CHAIN_ID,
  BLOCKCHAIN_POLYGON_CHAIN_ID,
  BLOCKCHAIN_RINKEBY_CHAIN_ID,
  BLOCKCHAIN_ROPSTEN_CHAIN_ID,
} from "./coreconstants";

export const itemEvents: any = {
  [ITEM_EVENT_TYPE_MINT] : "Mint",
  [ITEM_EVENT_TYPE_LISTINGS] : "Listing",
  [ITEM_EVENT_TYPE_SALES] : "Sale",
  [ITEM_EVENT_TYPE_BUY_OFFERS] : "Offer",
  [ITEM_EVENT_TYPE_BIDS] : "Bid",
  [ITEM_EVENT_TYPE_TRANSFERS] : "Transfer",
  [ITEM_EVENT_TYPE_LISTING_CANCEL] : "Listing Cancel",
  [ITEM_EVENT_TYPE_BUY_OFFER_CANCEL] : "Offer Cancel",
  [ITEM_EVENT_TYPE_BID_CANCEL] : "Bid Cancel",
}

export const LanguageList = [
  {
    name: "English",
    value: "en",
  },
  {
    name: "Español",
    value: "es",
  },
];

export const ALLOWED_FILE_TYPES = {
  image: ["image/png", "image/jpeg", "image/gif", "image/svg+xml"],
  video: ["video/mp4", "video/mpeg", "video/webm"],
  audio: ["audio/mpeg", "audio/ogg", "audio/wav", "audio/x-wav"],
  _3d: ["application/octet-stream", ""],
};
export const ALLOWED_FILE_EXTENSIONS = {
  image: ["png", "jpeg", "jpg", "gif", "svg"],
  video: ["mp4", "m4a", "m4p", "m4b", "m4r", "m4v", "webm"],
  audio: ["mp3", "ogg", "wav"],
  _3d: ["glb"],
};

export const ACCEPTED_ASSET_TYPES_ALL = [
  ...ALLOWED_FILE_TYPES.image,
  ...ALLOWED_FILE_TYPES.video,
  ...ALLOWED_FILE_TYPES.audio,
  ...ALLOWED_FILE_TYPES._3d,
];

export const ACCEPTED_ASSET_EXTENSIONS_ALL = [
  ...ALLOWED_FILE_EXTENSIONS.image,
  ...ALLOWED_FILE_EXTENSIONS.video,
  ...ALLOWED_FILE_EXTENSIONS.audio,
  ...ALLOWED_FILE_EXTENSIONS._3d,
];
export const BlockchainSlugList = [
  BLOCKCHAIN_RINKEBY_SLUG,
  BLOCKCHAIN_ROPSTEN_SLUG,
  BLOCKCHAIN_GOERLI_SLUG,
  BLOCKCHAIN_KOVAN_SLUG,
  BLOCKCHAIN_BINANCE_TESTNET_SLUG,
  BLOCKCHAIN_MUMBAI_SLUG,
  BLOCKCHAIN_ETHEREUM_SLUG,
  BLOCKCHAIN_POLYGON_SLUG,
  BLOCKCHAIN_BINANCE_MAINNET_SLUG,
];

// blockchain chain & slugs mapping
export const CHAIN_SLUG_MAPPING = {
  [BLOCKCHAIN_RINKEBY_CHAIN_ID.toString()]: BLOCKCHAIN_RINKEBY_SLUG,
  [BLOCKCHAIN_ROPSTEN_CHAIN_ID.toString()]: BLOCKCHAIN_ROPSTEN_SLUG,
  [BLOCKCHAIN_GOERLI_CHAIN_ID.toString()]: BLOCKCHAIN_GOERLI_SLUG,
  [BLOCKCHAIN_KOVAN_CHAIN_ID.toString()]: BLOCKCHAIN_KOVAN_SLUG,
  [BLOCKCHAIN_BINANCE_TESTNET_CHAIN_ID.toString()]:
    BLOCKCHAIN_BINANCE_TESTNET_SLUG,
  [BLOCKCHAIN_MUMBAI_CHAIN_ID.toString()]: BLOCKCHAIN_MUMBAI_SLUG,
  [BLOCKCHAIN_ETHEREUM_CHAIN_ID.toString()]: BLOCKCHAIN_ETHEREUM_SLUG,
  [BLOCKCHAIN_POLYGON_CHAIN_ID.toString()]: BLOCKCHAIN_POLYGON_SLUG,
  [BLOCKCHAIN_BINANCE_MAINNET_CHAIN_ID.toString()]:
    BLOCKCHAIN_BINANCE_MAINNET_SLUG,
};
